# Generated by Django 5.0.1 on 2024-02-17 19:45

import softuni_petstagram.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_petphoto_created_at_petphoto_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[softuni_petstagram.photos.models.MaxFileSizeValidator(limit_value=5242880)]),
        ),
    ]
